apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: {{ .Values.name }}
spec:
  image: {{ .Values.postgres }}
  postgresVersion: {{ .Values.postgresVersion }}
  instances:
    - name: instance1
      replicas: 2
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: {{ .Values.pvcs.instances.storageSize }}
        storageClassName: {{ .Values.pvcs.instances.storageClassName }}
  backups:
    pgbackrest:
      image: {{ .Values.pgBackRest}}
      repoHost:
        dedicated: {}
      repos:
      - name: repo1
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: {{ .Values.pvcs.repos.storageSize }}
            storageClassName: {{ .Values.pvcs.repos.storageClassName }}
  proxy:
    pgBouncer:
      image: {{ .Values.pgBouncer}}
  patroni:
    dynamicConfiguration:
      postgresql:
        parameters:
          max_parallel_workers: 2
          max_worker_processes: 2
          shared_buffers: 1GB
          work_mem: 2MB
  {{- with .Values.users }}
  users:
    {{- toYaml . | nindent 4}}
  {{- end }}
