namespace: postgres-operator

commonLabels:
  postgres-operator.crunchydata.com/control-plane: postgres-operator

bases:
- crd
- rbac/cluster
- manager

images:
- name: postgres-operator
  newName: registry.developers.crunchydata.com/crunchydata
  newTag: ubi8-5.0.0-alpha.4-0
